export const LAYOUT_DEFAULTS = {
  EMAIL_WIDTH: 600,
  SECTION_PADDING_X: 20,
  SECTION_PADDING_Y: 12,
  HEADING_MARGIN_BOTTOM: 16,
  PARAGRAPH_MARGIN_BOTTOM: 12,
  BUTTON_MARGIN_TOP: 24,
  SOCIAL_ICON_SPACING: 6,
  DEFAULT_LINE_HEIGHT: 1.6,
  DEFAULT_FONT_FAMILY: "Arial, sans-serif",
  BORDER_RADIUS: 8,
};
